### ISSUE TITLE
Multiple Streamable UIs Disappear in Production Builds When Calling .done()

### ISSUE THREAD

**Issue by amcclure-super** [vercel/ai#1558]
### Description

When nesting createStreamableUI values inside another createStreamableUI, the final result disappears in production builds.  The issue does not surface in local development.

Here is a reproducible example which works in dev but not after running `pnpm build`: https://github.com/amcclure-super/ai-streamableUI

Here are a couple videos. The first video in a dev build shows that the values do not disappear after marking ui.done().  The second video shows the values disappearing after ui.done() is called in a production build.

In dev, the UI does not disappear after ui.done():
https://github.com/vercel/ai/assets/60630426/ed2d927b-2586-4bd1-89c6-874b0da84e1a

In a production build, the UI disappears after ui.done() is called:
https://github.com/vercel/ai/assets/60630426/d52606be-c4fb-4374-9672-867869adf3f3

### Code example

Full repo: https://github.com/amcclure-super/ai-streamableUI

Relevant code:
page.tsx
`"use client";

import { useState } from "react";
import { ClientMessage } from "./actions";
import { useActions, useUIState } from "ai/rsc";
import { nanoid } from "nanoid";

export default function Home() {
  const [input, setInput] = useState<string>("");
  const [conversation, setConversation] = useUIState();
  const { submitUserMessage } = useActions();

  return (
    <div>
      <div>
        {conversation.map((message: ClientMessage) => (
          <div key={message.id}>
            {message.role}: {message.display}
          </div>
        ))}
      </div>

      <div>
        <input
          type="text"
          value={input}
          onChange={(event) => {
            setInput(event.target.value);
          }}
        />
        <button
          onClick={async () => {
            setConversation((currentConversation: ClientMessage[]) => [
              ...currentConversation,
              { id: nanoid(), role: "user", display: input }
            ]);

            const message = await submitUserMessage(input);

            setConversation((currentConversation: ClientMessage[]) => [
              ...currentConversation,
              message
            ]);
          }}
        >
          Send Message
        </button>
      </div>
    </div>
  );
}
`

actions.tsx
`import "server-only";

import { createAI, createStreamableUI } from "ai/rsc";
import { ReactNode } from "react";

export interface ServerMessage {
  role: "user" | "assistant";
  content: string;
}

export interface ClientMessage {
  id: string;
  role: "user" | "assistant";
  display: ReactNode;
}

export async function submitUserMessage(userInput: string) {
  "use server";

  let ui, uiStreams;
  try {
    ui = createStreamableUI(<div>Loading...</div>);

    (async () => {
      try {
        ui.update(<div>UI Update 1</div>);
        uiStreams = Array.from({ length: 3 }).map((_, i) => {
          return createStreamableUI(<div>Nested {i}</div>);
        });

        await new Promise((resolve) => setTimeout(() => resolve(true), 3000)); // wait 3 seconds

        ui.update(
          <div>
            Composed UI{" "}
            {uiStreams.map((u) => {
              return u.value;
            })}
          </div>
        );
        await new Promise((resolve) => setTimeout(() => resolve(true), 3000)); // wait 3 seconds
      } catch (e) {
      } finally {
        for (let i = 0; i < uiStreams?.length ?? 0; i++) {
          uiStreams[i].done();
        }
        ui.done();
      }
    })();
  } catch (e) {}

  return {
    id: Date.now(),
    display: <div>{ui.value}</div>
  };
}

export type QueryResult = {
  columns: string[];
  results: (number | string)[][];
};

const initialAIState: {
  role: "user" | "assistant" | "system" | "function";
  content: string;
  id?: string;
  name?: string;
}[] = [];

const initialUIState: {
  id: number;
  display: React.ReactNode;
}[] = [];

export const AI = createAI({
  actions: {
    submitUserMessage
  },
  initialUIState,
  initialAIState
});
`

**Comment by armando-immunefi** [comment]
confirming this on nextjs 14.2.3

**Comment by amithmkini** [comment]
Same here. I should also add that nested streamable UIs were working in Next.js 14.1.3

**Comment by lionelrudaz** [comment]
Same issue with AI 3.1.9 and Next 14.2.2.

My product is not yet on production, so that's OK, but that's bummer if you rely on this feature 😅

I hope there will be a fix soon. Let us know if we can provide more details.

**Comment by allenchuang** [comment]
Same thing here... locally it works fine not sure what the issue is. If someone is willing to drop a hint I'd be welcome to help take a look

**Comment by unstubbable** [comment]
This issue has been fixed in React, and will be provided with the upcoming Next.js release. You can verify that in your repro with these commands:

```sh
npm add next@canary react@beta react-dom@beta --legacy-peer-deps
npm run build && npm start
```

Reference:
- https://github.com/facebook/react/pull/28669
- https://github.com/facebook/react/pull/28780

Related:
- https://github.com/vercel/ai/issues/1627

**Comment by allenchuang** [comment]
Thank you so much! You're a hero 🫡

**Comment by lionelrudaz** [comment]
Thanks @unstubbable, that's awesome. Can you point to the Next.js release that we'll have to upgrade to? Will it be 14.3.0 or a minor release of 14.2?

**Comment by unstubbable** [comment]
Just looking in from the outside, it appears that the team is currently in the process of preparing the release of Next.js 15, which will include React 19. The aforementioned React fixes have been integrated here: https://github.com/vercel/next.js/pull/65058

**Comment by allenchuang** [comment]
hey @unstubbable i actually tested by upgrading to your suggested versions

```
npm add ai zod next@canary react@beta react-dom@beta --legacy-peer-deps
npm run build && npm start
```

however, this not only doesn't solve it, the issue now appears locally.. 🤔 any ideas here?

**Comment by unstubbable** [comment]
Did you test it with https://github.com/amcclure-super/ai-streamableUI, or somewhere else?

**Comment by allenchuang** [comment]
I tested in my own app where i'm using function_calling to call external APIs to get back a response. Does it have to use the repo?

**Comment by unstubbable** [comment]
> I tested in my own app based on https://github.com/vercel/ai-chatbot where i'm using function_calling to call external APIs to get back a response. Does it have to be the repo above?

No, but if the update doesn't help your case it's possible that you have a different situation. In this case it might make sense to create a separate issue with your own minimal reproduction.

**Comment by lionelrudaz** [comment]
I'm still a bit confused with this one. Should we wait for Next.js 15 to be released or is there a suitable workaround for this? It's still in the docs, so it's supposedly supported, right?

**Comment by lionelrudaz** [comment]
OK so it seems to work on AI SDK 3.1.x. But when you upgrade to 3.2.x, it breaks again.

Any ideas how we can fix that? That's quite annoying as it's in the docs, it's working fine locally and breaks only when deploying to production...

**Comment by amcclure-super** [comment]
Are you running next release candidate @lionelrudaz ?  3.2.x is working for me in production

**Comment by lionelrudaz** [comment]
Hey @amcclure-super, no I'm using Next 14.2.4. I had to specify this version as it was working with it.

What's your Next version?

**Comment by lionelrudaz** [comment]
I'm trying to upgrade to 3.3.3, and I still have exactly the same issue. Upgraded to Next 14.2.5, still the same.

You can see it live on my test server: https://release.tasters.ch/

Tell me if you need me to share some pieces of code.

**Comment by Preetnagda** [comment]
Similar issue, got fixed after upgrading to:

"next": "15.1.5"
"react": "19.0.0-rc.1",
"react-dom": "19.0.0-rc.1"

Also, using ai 4.1.0

**Comment by aayush-kapoor** [comment]
Marking this as closed for now - if you face any regression or have a similar problem after migrating to the latest AI SDK version, please feel free to open a new issue (with possible reproduction)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete production-only failure of existing streamable UI behavior, associated with React/Next.js versions rather than a request for new functionality.

### Evidence
- Nested createStreamableUI values disappear when .done() is called in production builds, while working in development.
- The report includes a reproducible repository, code, and videos demonstrating the failure.
- Multiple commenters reproduced the behavior across AI SDK 3.x and Next.js 14.x; later comments indicate upgrading to Next.js 15 and React 19 resolves it.
