### ISSUE TITLE
AI sdk v5 has insanely slow TypeScript performance

### ISSUE THREAD

**Issue by niels-bosman** [vercel/ai#7431]
### Description

On my Macbook Pro M3 I cannot get my type checker up in files that use 'ai'. I think there must be a performance bottleneck somewhere.

<img width="663" height="523" alt="Image" src="https://github.com/user-attachments/assets/ff5bb296-cfa6-448e-8ecd-663970869ced" />

### AI SDK Version

"@ai-sdk/azure": "2.0.0-beta.11"
"@ai-sdk/react": "2.0.0-beta.25"
"ai": "5.0.0-beta.25"

**Comment by nicoalbanese** [comment]
hmm I haven't seen any of this across multiple projects and multiple machines (including base m1 configuration). Is this on an existing project that you are upgrading?

**Comment by niels-bosman** [comment]
@nicoalbanese Yes, this is in a decently sized monorepo, we never had any issues like this so far.

**Comment by niels-bosman** [comment]
@nicoalbanese @lgrammel Might be related?

```
./src/app/api/chat/tools/create-slide.ts:24:32
Type error: Type instantiation is excessively deep and possibly infinite.

  22 | export type CreateSlideArgs = z.infer<typeof createSlideSchema>;
  23 |
> 24 | export const createSlideTool = tool({
```

Get this when building the application...

**Comment by niels-bosman** [comment]
Update: I think resolved by bumping zod to the latest v3

<img width="1295" height="259" alt="Image" src="https://github.com/user-attachments/assets/fbcc76eb-f49c-4b32-956e-8138e3cc9a93" />

**Comment by dancer** [comment]
good to hear let us know if any more issues

**Comment by wilsonowilson** [comment]
This is happening to me now. I set up the AI sdk v5 with zod v4 yesterday and it worked just fine, but today I can't use my editor at all for some reason due to the ts server crashing.

Tested on 
"ai": "5.0.0-beta.12",
"zod": "^4.0.7"

I tried upgrading to @niels-bosman's version of zod, but this didn't fix it.

**Comment by wilsonowilson** [comment]
Upgrading to 5.0.0-beta.25 appears to have fixed this for me (for now)

**Comment by isaacpz** [comment]
Happening for us too, using `5.0.0-beta.25` (as well as `5.0.0-beta.28`) and zod `3.25.76`. 

For us, it seems specific to this call:
```
        const { object } = await generateObject<z.ZodType<TReturnType>>({
          ...compiled,
          ...this.getAiSdkLanguageModelFromModelName(compiled),
          messages: inputMessages,
          schema: schema,
          experimental_telemetry: {
            isEnabled: true,
            metadata: {
                 custom_metadata: 1
            },
          },
        });
```

The file where Typescript is slow has many vercel AI calls (streamText, generateText, etc) but this one in particular seems to be causing problems.

**Comment by lgrammel** [comment]
This happens when you import `import { z } from "zod"`

In AI SDK 5, you need to either

`import { z } from "zod/v4";` or
`import { z } from "zod/v3";`

**Comment by colinhacks** [comment]
If you have been experiencing this, it's because you're using legacy tsconfig settings, namely `moduleResolution: "node"`. There's no reason to be using this anymore. The root cause was a very subtle resolution bug that caused both ESM and CJS versions of Zod to be loaded in the codebase simultaneously. TypeScript considers these independent constructs, resulting in  assignability issues and associated slow TS performance and occasionally OOM errors.

The simplest fix for this is to upgrade to a modern `moduleResolution` setting: https://www.typescriptlang.org/tsconfig/#moduleResolution. The old `"node"` setting mirrored the behavior of Node 10 which hit EOL in 2021.

That said, I found a mitigation on Zod's end that also resolves this issue. Upgrade to `zod@4.1.6` and you won't hit this anymore: https://github.com/colinhacks/zod/pull/5222

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete TypeScript performance and stability failure encountered when using AI SDK 5, even though later comments identify Zod/module-resolution compatibility as the underlying cause and provide workarounds.

### Evidence
- AI SDK 5 usage caused TypeScript language-service hangs, crashes, excessive type-instantiation errors, and occasional OOM failures.
- Multiple users reproduced the slowdown with AI SDK 5 and Zod 3 or 4.
- The cause was traced to TypeScript loading both Zod ESM and CJS types under legacy `moduleResolution: "node"`; modern module resolution or Zod 4.1.6 mitigates it.
